// Dependencies
import { useDispatch } from "react-redux";
import { Accordion, AccordionItem } from "@nextui-org/react";

// Local Files

import { scrollTop } from "../../utils/controllers";
import Intro from "../../globalSubComponents/Intro";
import { updateTab } from "../../Redux/Slices/curTabSlice";

// const definations = [
//   `Account means a unique account created for You to access our Service or parts of our Service`,
//   `Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control"
//     means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of
//     directors or other managing authority`,
//   `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to  HMS Freedom LLC, Unit-544, McCabe Street, Port Charlotte, Florida, USA..`,
//   `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing
//     the details of Your browsing history on that website among its many uses.`,
//   `Country refers to: Uttarakhand, India`,
//   `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet`,
//   `Personal Data is any information that relates to an identified or identifiable individual.`,
//   `Service refers to the Website.`,
//   `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to
//     third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on
//     behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the
//     Service is used.`,
//   `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service
//     infrastructure itself (for example, the duration of a page visit).`,
//   `Website refers to Shop Nest, accessible from https://www.hmsfreedom.com/`,
//   `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual
//     is accessing or using the Service, as applicable.
//     `,
// ];

// const personalData = [
//   " First name and last name",
//   " Phone number",
//   " Address, State, Province, ZIP/Postal code, City",
//   " Usage Data",
// ];

const useData = [
  "To provide and maintain our Service, including to monitor the usage of our Service",
  "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user",
  "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service",
  "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation",
  "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
];

const shareData = [
  "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You",
  "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company",
  "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us",
  "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.",
  "With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside",
  "With Your consent: We may disclose Your personal information for any other purpose with Your consent.",
];

const legalRequirements = [
  "Comply with a legal obligation",
  "Protect and defend the rights or property of the Company",
  "Prevent or investigate possible wrongdoing in connection with the Service",
  "Protect the personal safety of Users of the Service or the public",
  "Protect against legal liability",
];

const Privacy = () => {
  const dispatch = useDispatch();
  dispatch(updateTab("Privacy"));
  scrollTop();

  return (
    <>
      <div className="h-[12rem] w-full flex justify-center items-center p-[5rem] bg-slate-400 text-black">
        <h1 className="text-4xl font-bold ">Privacy & Policy</h1>
      </div>
      <div className="h-auto md:p-[5rem] p-[2rem] flex flex-col items-start justify-between">
        <h3 className="font-semibold py-[0.5rem]">Privacy Policy for ShopNest Ecommerce App</h3>
        <p className="text-gray-600 py-[0.5rem]">
          At ShopNest, we are committed to protecting the privacy and security of our users' personal information. This
          Privacy Policy outlines the types of information we collect, how we use it, and the steps we take to safeguard
          it.
        </p>
        <div className="py-[1rem]">
          <h3 className="font-semibold">Information We Collect:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                Personal Information: When you register for an account on our app, we may collect personal information
                such as your name, email address, phone number, and shipping address.
              </li>
              <li className="py-[0.5rem]">
                Payment Information: If you make a purchase through our app, we will collect payment information such as
                credit card details or other payment method details.
              </li>
              <li className="py-[0.5rem]">
                Device Information: We may collect information about the device you use to access our app, including
                your device's unique identifier, IP address, and operating system.
              </li>
              <li className="py-[0.5rem]">
                Usage Information: We may collect information about how you use our app, including the pages you visit,
                the products you view, and your interactions with our features and advertisements.
              </li>
              <li className="py-[0.5rem]">
                Location Information: With your consent, we may collect your precise or approximate location information
                to provide you with location-based services, such as personalized recommendations or local store
                availability.
              </li>
            </ul>
          </div>
        </div>
        <div className="py-[1rem]">
          <h3 className="font-semibold">How We Use Your Information:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                To Provide Services: We use the information we collect to provide you with the services offered through
                our app, including processing orders, delivering products, and responding to customer inquiries.
              </li>
              <li className="py-[0.5rem]">
                To Improve Our App: We may use aggregated and anonymized data to analyze trends and user behavior, which
                helps us improve the functionality and user experience of our app.
              </li>
              <li className="py-[0.5rem]">
                To Personalize Your Experience: We may use your information to personalize your experience on our app,
                such as displaying personalized product recommendations or promotions based on your browsing history and
                preferences.
              </li>
              <li className="py-[0.5rem]">
                Usage Information: We may collect information about how you use our app, including the pages you visit,
                the products you view, and your interactions with our features and advertisements.
              </li>
              <li className="py-[0.5rem]">
                To Communicate with You: We may use your contact information to communicate with you about your account,
                orders, promotions, and updates to our Privacy Policy and Terms of Service.
              </li>
            </ul>
          </div>
        </div>
        <div className="py-[1rem]">
          <h3 className="font-semibold">How We Protect Your Information:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                Data Security: We implement reasonable security measures to protect the confidentiality and integrity of
                your personal information, including encryption, access controls, and regular security audits.
              </li>
              <li className="py-[0.5rem]">
                Third-Party Service Providers: We may engage third-party service providers to assist us in providing and
                improving our services. These service providers are contractually obligated to protect your information
                and only use it for the purposes specified by us.
              </li>
              <li className="py-[0.5rem]">
                Data Retention: We retain your personal information for as long as necessary to fulfill the purposes
                outlined in this Privacy Policy, unless a longer retention period is required or permitted by law.
              </li>
            </ul>
          </div>
        </div>
        <div className="py-[1rem]">
          <h3 className="font-semibold">Your Choices:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                Account Information: You can update or delete your account information at any time by accessing your
                account settings in the app.
              </li>
              <li className="py-[0.5rem]">
                Opt-Out: You can opt-out of receiving promotional emails or push notifications from us by adjusting your
                notification preferences in the app settings.
              </li>
            </ul>
          </div>
        </div>
        <div className="py-[1rem]">
          <h3 className="font-semibold">Changes to This Privacy Policy:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                We may update this Privacy Policy from time to time to reflect changes in our practices or applicable
                laws. We will notify you of any material changes by posting the updated Privacy Policy on our website or
                app and updating the "Last Updated" date.
              </li>
            </ul>
          </div>
        </div>
        <div className="py-[1rem]">
          <h3 className="font-semibold">Contact Us:</h3>
          <div className="py-[0rem]">
            <ul className="text-gray-600 list-disc px-[2rem]">
              <li className="py-[0.5rem]">
                If you have any questions or concerns about our Privacy Policy or our privacy practices, you can contact
                us at contact@email.com.
              </li>
              <li className="py-[0.5rem]">
                By using our app, you agree to the collection and use of your information as outlined in this Privacy
                Policy.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
};

export default Privacy;
